### PR TITLE
Update and fix dependencies.

### PR DESCRIPTION
**Pull request by gijskant**
The main idea is to update the dependencies of `tmtk`.
I also removed the testing of compatibility with different versions of `pandas`.
Is there any reason why multiple versions should be supported? Typically it is good
to always require the latest version.

I see no documentation of the release process. It would be good to publish wheels to PyPI.
Also, PyPI has version 0.5.6 and Anaconda has version 0.5.5. Is there a reason for this?

### CODE REVIEW

**Review by jochemb — CHANGES_REQUESTED** [review]
Thanks for having a look at the dependencies situation. 

Though I agree it is best to encourage using latest version of these packages, in the past we have had environments where we could have full control over pandas installations and were sometimes forced to use older version of pandas with a newer version of tmtk. Testing multiple versions of pandas was supposed to help with reducing the number of breaking changes, though I do not think this has occurred yet since pandas 0.20. 

Also your PR pins the dependencies to a specific version, which is not a good practise here. Some workflow that uses tmtk might require a newer version of one of the dependencies and then we would break that workflow, we shouldn't be more strict than we have to be. If we would use tmtk as part of a specific project pipeline, we should apply strictly pinned versions tmtk and all its dependencies there. I would keep the looser `>=`, could you agree with that?

Publishing to Anaconda is done using conda-forge: https://github.com/conda-forge/tmtk-feedstock 
This requires some manual checks (on the build dependencies). Are you aware of anyone using the anaconda version?

**Comment by gijskant** [comment]
I updated all dependencies to the latest and I expected that to happen regularly.

**Comment by gijskant** [comment]
I'm not sure Anaconda is being used, it was mentioned in requirements for data loading at UCB. But I would guess that pip would work equally well.

**Comment by gijskant** [comment]
The thing is that functionality may also break with newer version of packages.

**Comment by gijskant** [comment]
I would say, we declare dependencies with versions that we tested with. Pip/conda should fail if there are conflicting dependencies. The solution then should be to update dependencies to the latest versions again (and possibly fix for breaking changes).

**Review by jochemb — APPROVED** [review]

**Review by Spayralbe — APPROVED** [review]

**Comment by gnarula** [comment]
@gijskant could you please publish a new version with the updated `requirements.txt`? The current one fetches the latest version of pandas which isn't compatible.

**Comment by gijskant** [comment]
@gnarula A new version is now published on PyPI, v0.5.8: https://pypi.org/project/tmtk/. Could you this version?

**Pull request merged**
